FROM node:18-bullseye-slim AS build
USER root
WORKDIR /usr/src/app
COPY ./web-app/ /usr/src/app/
RUN npm install -g vite && \
    npm install && \
    vite build --base=/manage

ENTRYPOINT ["cp", "-a", "/usr/src/app/dist/.", "/dist/"]
VOLUME /dist